---
title: "EDA for Electricity Dataset"
author: "Kendall Beaver"
date: "2024-06-19"
output: html_document
---

# Electricity Wholesale Analysis (2014-2024)

Resource: <https://www.eia.gov/electricity/wholesale/>

## Load Library

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(dplyr)
```

## 2014-2024 Datasets

Import all datasets into their own variables.

```{r 2014-2015}

data_2014 <- read_excel ("./Data/ice_electric-2014final.xls")

data_2014

data_2015 <- read_excel ("./Data/ice_electric-2015final.xls")
data_2015

data_2016 <- read_excel ("./Data/ice_electric-2016final.xls")
data_2016

data_2017 <- read_excel ("./Data/ice_electric-2017final.xlsx")
data_2017

data_2018 <- read_excel ("./Data/ice_electric-2018final.xlsx")
data_2018

data_2019 <- read_excel ("./Data/ice_electric-2019final.xlsx")
data_2019

data_2020 <- read_excel ("./Data/ice_electric-2020final.xlsx")
data_2020

data_2021 <- read_excel ("./Data/ice_electric-2021final.xlsx")
data_2021

data_2022 <- read_excel ("./Data/ice_electric-2022final.xlsx")
data_2022 <- select(data_2022, -'Trade date') # REMOVE COLUMN because it's bad
data_2022$'Trade date' <- data_2022$`Delivery start date` - 86400
data_2022 <- data_2022 %>% select(1, `Trade date`, everything()) # Make 'Trade date' the 2nd column like all the other datasets
data_2022

data_2023 <- read_excel ("./Data/ice_electric-2023final.xlsx")
data_2023

data_2024 <- read_excel ("./Data/ice_electric-2024.xlsx")
data_2024
```

## Head 2014-2024

```{r head}

#head(data_2014)
#head(data_2015)
#head(data_2016)
#head(data_2017)
#head(data_2018)
#head(data_2019)
#head(data_2020)
#head(data_2021)
#head(data_2022)
#head(data_2023)
#head(data_2024)

unique(data_2014$`Price hub`) 
# Need to correct "Nepool MH Da LMP Peak" to "Nepool MH DA LMP Peak"
# Need to correct "NP 15 EZ..." to "NP15 EZ Gen..."
# Correct "Palo Verde" to "Palo Verde Peak"
# Change "SP-15 Gen DA LMP Peak" to "SP15 EZ Gen DA LMP Peak"

# Indiana Hub RT Peak
# Mid C Peak
# Nepool MH DA LMP Peak
# NP15 EZ Gen DA LMP Peak
# Palo Verde Peak
# PJM WH Real Time Peak
# SP15 EZ Gen DA LMP Peak

unique(data_2015$`Price hub`) 
# 8 Peaks
# Extra Peak from 7 Peaks below: ERCOT North 345KV Peak
unique(data_2016$`Price hub`)
# 8 Peaks
# Extra Peak from 7 Peaks below: ERCOT North 345KV Peak
unique(data_2017$`Price hub`)
# 8 Peaks
# Extra Peak from 7 Peaks below: ERCOT North 345KV Peak
unique(data_2018$`Price hub`)
# 8 Peaks
# Extra Peak from 7 Peaks below: ERCOT North 345KV Peak
unique(data_2019$`Price hub`)
# 8 Peaks
# Extra Peak from 7 Peaks below: ERCOT North 345KV Peak

unique(data_2020$`Price hub`) # 7 Peaks
unique(data_2021$`Price hub`) # 7 Peaks
unique(data_2022$`Price hub`) # 7 Peaks
unique(data_2023$`Price hub`) # 7 Peaks
unique(data_2024$`Price hub`) # 7 Peaks

# Indiana Hub RT Peak
# Mid C Peak
# Nepool MH DA LMP Peak
# NP15 EZ Gen DA LMP Peak
# Palo Verde Peak
# PJM WH Real Time Peak
# SP15 EZ Gen DA LMP Peak
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
